apiVersion: v1
kind: ConfigMap
metadata:
  name: vue-history-nginx-cm
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  history.lyine.pw;

        #access_log  /var/log/nginx/host.access.log  main;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        #this is a config map test
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
